services:
  - type: web
    name: smartseason-api
    env: python
    plan: free
    buildCommand: pip install -r backend/requirements.txt && cd backend && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: cd backend && gunicorn smartseason.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: "3.9"
      - key: ALLOWED_HOSTS
        scope: runtime
        value: "smartseason-api.onrender.com,localhost"

databases:
  - name: smartseason-db
    plan: free
    version: "14"
    initializer:
      command: cd backend && python manage.py migrate
