# Generated by Django 4.2.30 on 2026-04-24 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='environmental_conditions',
            field=models.JSONField(blank=True, default=list, help_text='List of environmental conditions: stress, drought, pest, disease, damage, wilting, none'),
        ),
    ]
